variable "aws_account_id" {
  description = "AWS account ID used in IAM role ARNs"
  type        = string
}

variable "storage_credential_external_id" {
  description = "External ID generated by Databricks when creating the storage credential"
  type        = string
}