name: earthquake_pipeline

profile: earthquake_pipeline

model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  earthquake_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: incremental
    marts:
      +materialized: table
