name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform-checks:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.8"

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate -no-color

  dbt-checks:
    name: dbt Project Parse
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt/earthquake_pipeline
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Create dummy profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          earthquake_pipeline:
              target: dev
              outputs:
                dev:
                    type: databricks
                    catalog: dummy_catalog
                    schema: dummy_schema
                    host: dummy.cloud.databricks.com
                    http_path: /dummy/path
                    token: dummy_token
          EOF
      - name: Install & Parse
        run: |
          pip install dbt-databricks
          dbt deps
          dbt parse
